name: unit test

on: [push, pull_request]

env:
  CONDA_ENV: xrsignal

jobs:
  unit_test:
    name: ${{ matrix.python-version }}-unit-test
    runs-on: ubuntu-20.04
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
        experimental: [false]
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch all history for all branches and tags.
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Print conda env
      shell: bash -l {0}
      run: |
        conda info
        conda list
    - name: Install pytest
      shell: bash -l {0}
      run: |
        python -m pip install pytest
    - name: Install xrsignal
      shell: bash -l {0}
      run: |
        python -m pip install -e .
    - name: Run unit tests
      shell: bash -l {0}
      env:
        FORCE_COLOR: 3
      run: pytest -vv tests |& tee unit_test_log${{ matrix.python-version }}.log
    - name: Upload unit test log
      if: ${{ success() || failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: unit_test_log${{ matrix.python-version }}
        path: unit_test_log${{ matrix.python-version }}.log